Fix build signature to not return always-nil error
wavefrontHQ/observability-for-kubernetes pull request #117
Opened 2023-04-05 20:58 UTC by jessepye

2023-06-20 14:41 UTC, m25n requested changes

2023-06-20 14:41 UTC, m25n commented on collector/plugins/sources/prometheus/prometheus.go
>  		return result, err
Why not just return nil for the result here (instead of a TODO comment)?

2023-06-20 14:41 UTC, m25n commented on collector/plugins/sources/prometheus/prometheus.go
>  	return points, err
If there is an error, we might consider returning nil points here as well.

2023-06-20 14:41 UTC, m25n commented on collector/plugins/sources/prometheus/prometheus.go
> +		// so whatever happens to be the last value of err is what is returned
Should we fix the error message to accommodate multiple failures? Perhaps using something like [`errors.Join`](https://pkg.go.dev/errors#Join)?

2023-12-15 21:16 UTC, jerrybelmonte commented
Abandoning stale PR.

2023-12-15 21:16 UTC, closed without merging